import { Toaster } from "@/components/ui/sonner";
import { ThemeSwitch } from "@/components/ui/theme-switch-button";
import Navbar from "@/features/navigation/navbars";
import type { Metadata } from "next";
import { Geist_Mono, Montserrat } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${geistMono.variable} font-sans antialiased`}
      >
        <NuqsAdapter>
          <div className="fixed top-4 right-4 z-50">
            <ThemeSwitch />
          </div>
          <Navbar />
          <main
            style={{ paddingLeft: "var(--sidebar-width, 240px)" }}
            className="hidden lg:block"
          >
            {children}
          </main>
          <main className="lg:hidden">{children}</main>
          <Toaster position="top-center" richColors />
        </NuqsAdapter>
      </body>
    </html>
  );
}
